/******************************************************************************
    Given a keyword of unique alphabets and a text, write a program to encrypt 
    the text using the keyword. Cipher text is generated by arranging the elements 
    of the text below the keyword and combining them column wise. The columns should 
    be picked based on the alphabetical order of the characters in the keyword
    
    Assume, given keyword is PAS and text is ILIKECODE, place all the characters of the 
    text in the below format.

        PAS
        ILI
        KEC
        ODE
        The cipher text will be ALEDPIKOSICE
        
        Input format :
        The first line gives the Keyword. The second line gives the text that needs to be 
        encrypted. Read the input from standard input.
        
        Output format :
        Print the cipher text to standard output.

*******************************************************************************/




import java.io.*;
import java.util.*;

class Main
{
    public static String cipher(String input,String key){
        int inpN,keyN;
        inpN = input.length();
        keyN = key.length();
        int rows;
        if(inpN%keyN != 0){
            rows = inpN/keyN +1;
        }
        else{
            rows = inpN/keyN;
        }
        
        char row[] = new char[keyN];
        char mat[][] = new char[rows+1][keyN];
        for(int i=0;i<keyN;i++){
            mat[0][i] = key.charAt(i);
        }
        
        int k= 0;
        for(int i=1;i<=rows;i++){
            for(int j=0;j<keyN && k<inpN;j++,k++){
                mat[i][j] = input.charAt(k);
            }
        }
        
        
        //System.out.println(letters);
        String alpha = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        int init =0;
        int res[] = new int[keyN];
        for(int i=0;i<26;i++){
            for(int j=0;j<keyN;j++){
                if(alpha.charAt(i)==key.charAt(j)){
                    res[j] = init;
                    init++;
                }
            }
        }
        StringBuilder ans = new StringBuilder("");
        for(int i=0;i<keyN;i++){
            for(int j=0;j<keyN;j++){
                if(i==res[j]){
                    for(int x=0;x<=rows;x++){
                        ans.append(mat[x][j]);
                    }
                }
            }
        }
        return ans.toString();
    }
    public static void main (String[] args) throws java.lang.Exception
    { 
        /*Scanner s = new Scanner(System.in);
        String inputString = s.nextLine();*/
        String input ="ILIKECODE";
        String key = "PAS";
        
        System.out.println(cipher(input,key));
    }
}
